-- V1: Create road_segments table (traffic-service)

CREATE TABLE IF NOT EXISTS road_segments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    city        VARCHAR(255) NOT NULL,
    start_lat   DOUBLE PRECISION NOT NULL,
    start_lng   DOUBLE PRECISION NOT NULL,
    end_lat     DOUBLE PRECISION NOT NULL,
    end_lng     DOUBLE PRECISION NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
