-- V2: Create traffic_data table (traffic-service)

CREATE TABLE IF NOT EXISTS traffic_data (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    road_segment_id     BIGINT NOT NULL,
    vehicle_count       INTEGER NOT NULL,
    avg_speed_kmh       DOUBLE PRECISION NOT NULL,
    congestion_level    VARCHAR(255) NOT NULL,
    source              VARCHAR(255) NOT NULL,
    recorded_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_traffic_data_road_segment
        FOREIGN KEY (road_segment_id) REFERENCES road_segments(id),
    CONSTRAINT traffic_data_vehicle_count_check
        CHECK (vehicle_count >= 0),
    CONSTRAINT traffic_data_avg_speed_kmh_check
        CHECK (avg_speed_kmh >= 0),
    CONSTRAINT traffic_data_congestion_level_check
        CHECK (congestion_level IN ('LOW', 'MEDIUM', 'HIGH', 'SEVERE')),
    CONSTRAINT traffic_data_source_check
        CHECK (source IN ('SENSOR', 'CAMERA', 'GPS', 'MANUAL', 'API'))
);
